// Common ATA chapters for defect reporting (A320 family).
export const ATA_CHAPTERS: { code: string; label: string }[] = [
  { code: '21', label: 'Air conditioning' },
  { code: '22', label: 'Auto flight' },
  { code: '23', label: 'Communications' },
  { code: '24', label: 'Electrical power' },
  { code: '25', label: 'Equipment / furnishings' },
  { code: '26', label: 'Fire protection' },
  { code: '27', label: 'Flight controls' },
  { code: '28', label: 'Fuel' },
  { code: '29', label: 'Hydraulic power' },
  { code: '30', label: 'Ice & rain protection' },
  { code: '31', label: 'Indicating / recording' },
  { code: '32', label: 'Landing gear' },
  { code: '33', label: 'Lights' },
  { code: '34', label: 'Navigation' },
  { code: '35', label: 'Oxygen' },
  { code: '36', label: 'Pneumatic' },
  { code: '38', label: 'Water / waste' },
  { code: '49', label: 'APU' },
  { code: '52', label: 'Doors' },
  { code: '56', label: 'Windows' },
  { code: '71', label: 'Power plant' },
  { code: '72', label: 'Engine' },
  { code: '73', label: 'Engine fuel & control' },
  { code: '74', label: 'Ignition' },
  { code: '75', label: 'Air (engine)' },
  { code: '76', label: 'Engine controls' },
  { code: '77', label: 'Engine indicating' },
  { code: '78', label: 'Exhaust' },
  { code: '79', label: 'Oil' },
  { code: '80', label: 'Starting' },
];
